spring.application.name=facturaarca
spring.datasource.url=jdbc:postgresql://localhost:5432/facturaarca
spring.datasource.username=postgres
spring.datasource.password=milanesa123

# CONFIGURACIÓN CLAVE PARA QUE SE CREEN LAS TABLAS:
spring.jpa.hibernate.ddl-auto=update

# Opcional para ver las consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=public
